apiVersion: v1
kind: Service
metadata:
  labels:
    run: btp
  name: btp-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31942
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    run: btp
  sessionAffinity: None
  type: NodePort