---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
  namespace: nuthan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: docker.io/8884654123/25p:latest
        imagePullPolicy: IfNotPresent
        name: producer
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: nuthan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: docker.io/8884654123/25c:latest
        imagePullPolicy: IfNotPresent
        name: consumer
        ports:
        - containerPort: 8081
