---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: nuthan
spec:
  ports:
  - port: 32181
  clusterIP: None
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: nuthan
spec:
  ports:
  - port: 29092
  clusterIP: None
  selector:
    app: kafka